### ISSUE TITLE
"Customise UUI" and "Select tools for UUI" nearly the same

### ISSUE THREAD

**Issue by ToonTalk** [ecraft2learn/learning-analytics#3]
![image](https://user-images.githubusercontent.com/2138696/50052521-b09ce200-0125-11e9-803e-e9a6f89499b1.png)

![image](https://user-images.githubusercontent.com/2138696/50052518-9c58e500-0125-11e9-9552-48b9b6e8c321.png)

and unclear what text to enter for the "Customise UUI"  option in the editor

**Comment by Calkin-eC2L** [comment]
can someone gives an explanation for this? the two menus seem to be a repetition
